name: PUBLISH

on:
  push:
    tags:
      - v*

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install twine wheel setuptools

      - name: Build
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
